### ISSUE TITLE
Make Language selectors work in conjunction with Category selected

### ISSUE THREAD

**Issue by yashjawale** [acesdit/snippets#20]
Currently the language buttons work independently irrespective of the category selected.

Make them work together in combination.
Like `Algorithms` -> `Python` will show only Algorithms written in python.

**Comment by yashjawale** [comment]
Proposed solution:
Handle Categories with routes like current implementation & filter languages using client side JavaScript.

**Comment by yashjawale** [comment]
<img width="692" alt="UI Mockup" src="https://github.com/acesdit/snippets/assets/63059729/19ef07b3-e3ec-452f-b508-f92c01899fa1">

**Comment by nnisarggada** [comment]
I'd like to work on this.
