### ISSUE TITLE
Add Dark mode to frontend

### ISSUE THREAD

**Issue by yashjawale** [acesdit/snippets#7]
Add automatic dark mode to web frontend.
The frontend uses TailwindCSS

Refer [https://tailwindcss.com/docs/dark-mode](https://tailwindcss.com/docs/dark-mode) for more information.

**Comment by Smitkhobragade** [comment]
Assign me this issue

**Comment by Smitkhobragade** [comment]
Yess working on it ..

**Comment by yashjawale** [comment]
Ok 👍

**Comment by Pumang18** [comment]
Can I work on this issue?

**Comment by Smitkhobragade** [comment]
@yashjawale you can assign this issue to @Pumang18 .. I am facing some errors in resolving the files..

**Comment by Pumang18** [comment]
I'd like to work on this.
